### ISSUE TITLE
benchmark script is only works for single token generation?

### ISSUE THREAD

**Issue by williamstar** [openppl-public/ppl.nn.llm#10]
How to set the output length for the llama7B benchmark script? It seems that the script is only profiing for single token generation.

**Comment by Alcanderian** [comment]
Now we add the full generation pipeline benchamrk for llama, #12 #13 #14

But this benchmark is model specified, it may not able to benchmark other models

**Comment by williamstar** [comment]
Thanks alot. I will have a try 😄
